AD_POPUP_CLOSE_BTN = "//button[@class='close close-popup-contact']"
ACCOUNT_ICON = "//a[@aria-label='Tài khoản']"
EMAIL_INPUT = "//input[@id='login-customer[email]']"
PASSWORD_INPUT = "//input[@id='login-customer[password]']"
LOGIN_BUTTON = "//button[@id='form_submit-login']"
HOMEPAGE_LOGO = "//div[@class='header-wrap-logo']"
PRODUCT_CATEGORY = "//nav[@class='navbar-mainmenu']/div[@class='danhmucsanpham']"
FIRST_CATEGORY = "//div[@class='postionabcat']/ul[1]/li[1]"
FIRST_PRODUCT = "//div[@class='templatecolreal']/div[1]/div/div/div[2]/h3"
SIZE_22G = "//label[text()='22g']"
QUANTITY_INPUT = "//input[@class='quantitynum']"
DECREASE_QUANTITY = "//div[@class='gridoftemplateaction']/div[1]/div/div[2]/div[1]"
INCREASE_QUANTITY = "//div[@class='gridoftemplateaction']/div[1]/div/div[2]/div[3]"
ADD_TO_CART = "//a[text()='Thêm vào giỏ hàng']"
CART_NOTE = "//textarea[@id='notecart']"
CHECKOUT_NOW = "//div[@class='thantoannga']/a"
FULL_NAME_INPUT = "//input[@id='billing_address_full_name']"
EMAIL_CHECKOUT_INPUT = "//input[@id='checkout_user_email']"
PHONE_INPUT = "//input[@id='billing_address_phone']"
ADDRESS_INPUT = "//input[@id='billing_address_address1']"
PROVINCE_SELECT = "//select[@id='customer_shipping_province']"
DISTRICT_SELECT = "//select[@id='customer_shipping_district']"
WARD_SELECT = "//select[@id='customer_shipping_ward']"
NEXT_BUTTON = "//div[@id='step-footer-checkout']//following::button"
FINISH_BUTTON = "//button[@data-event-added='attached']"
LOGOUT_LINK = "//a[text()='Đăng xuất']"