product_category = "//div[@class='danhmucsanpham']"
beauty_accessories = "//a[contains(@href, 'phu-kien-lam-dep')]"
add_to_cart = "//div[@class='gridoftemplateaction2']//a[contains(text(),'Thêm vào giỏ hàng')]"
shopping_cart = "//span[@class='box-icon' and @label='Giỏ hàng']"
INPUT_FULLNAME = "//input[@id='billing_address_full_name']"
INPUT_ADDRESS = "//input[@id='billing_address_address1']"
INPUT_EMAIL = "//input[@id='checkout_user_email']"
INPUT_PHONE = "//input[@id='billing_address_phone']"
BTN_Pay = "//button[contains(@class, 'step-footer-continue-btn') and .//span[text()='Tiếp tục đến phương thức thanh toán']]"
