product_category = "//nav[@class='navbar-mainmenu']//div[@class='danhmucsanpham']"
beauty_accessories = "//span[contains(text(),'Phụ Kiện Làm Đẹp')]"
type_product= "//div[@class='listmenuchuan']//a[contains(text(),'Phụ Kiện Tóc')]"
product_1 = "//a[text()='Kẹp Tóc Dây Xích']"
add_to_cart = "//a[contains(text(),'Thêm vào giỏ hàng')]"
shopping_cart = "//span[@class='box-icon' and @label='Giỏ hàng']"
pay_ment = "//div[@class='thantoannga']"
INPUT_FULLNAME = "//input[@id='billing_address_full_name']"
INPUT_ADDRESS = "//input[@id='billing_address_address1']"
INPUT_EMAIL = "//input[@id='checkout_user_email']"
INPUT_PHONE = "//input[@id='billing_address_phone']"

