
# url_booking = "(//span[text()='Booking']//parent::span//parent::a)[1]"
date_input= "//input[@id='date']"
time_input= "//input[@id='time']"
next_btn= "//button[@id='nextBtn']"
single_room_btn="//div[@id='single-rooms-container']/button[text()='ROOM 13']"
group_room_btn="//div[@id='couple-rooms-container']/button[text()='ROOM 04']"
wall_room_btn="//div[@id='walls-container']/button[text()='WALL 01']"
water_color ="//div[@id='waterColorBtn']"

white_color="//div[text()='White']"
red_color="//div[text()='Red']"
green_color="//div[contains(text(),'Green')]"
pink_color="//div[contains(text(),'Pink')]"
gray_color="//div[contains(text(),'Gray')]"
blue_color="//div[contains(text(),'Blue')]"
orange_color="//div[contains(text(),'Orange')]"
yellow_color="//div[contains(text(),'Yellow')]"
purple_color="//div[contains(text(),'Purple')]"
black_color="//div[contains(text(),'Black')]"
pastel_color="//div[contains(text(),'Pastel')]"
brown_color="//div[contains(text(),'Brown')]"

nextpage_btn="//button[text()='1']"
img_link="//img[@class='image_2']"
