url_home="//div[@class='main-header']//following-sibling::h1[@class='logo-text']"
advertise_btn="//button[@class='close close-popup-contact']"
url_menu_danhmucsp = "//nav[@class='navbar-mainmenu']/div[@class='danhmucsanpham']"
url_menu_product="//span[contains(text(),'Chăm Sóc Da Mặt')]"
url_type_product="//div[@class='listmenuchuan']/div[1]/a[contains(text(),'Tẩy Trang')]"
url_product="//a[text()='Dầu Tẩy Trang Manyo Pure Cleansing Oil']"
url_add_product="//a[text()='Thêm vào giỏ hàng']"
url_payment="//div[@class='thantoannga']"
fullname_input="//input[@id='billing_address_full_name']"
email_input="//input[@id='checkout_user_email']"
phone_input="//input[@id='billing_address_phone']"
address_input="//input[@id='billing_address_address1']"
province_select="//select[@id='customer_shipping_province']"
district_select="//select[@id='customer_shipping_district']"
ward_select="//select[@id='customer_shipping_ward']"
submit_btn="//form[@id='form_next_step']/button"
checkout_complete_btn="//form[@id='checkout_complete']/button"
input_search="//input[@id='inputSearchAuto-3']"
search_btn ="//form[@class='searchform-product searchform-categoris ultimate-search']//button[@class='btn-search btn']"